development:
  adapter: postgresql
  database: blog_joao_development
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000
  template: template0

test: &test
  adapter: postgresql
  database: blog_joao_test
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000
  template: template0

production:
  adapter: postgresql
  database: blog_joao_production
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000
  template: template0

cucumber:
  <<: *test

